### ISSUE TITLE
undefined method `find_by' for Model:Class

### ISSUE THREAD

**Issue by ryabrody** [local-ch/lhs#105]
_Reproduce_
Model with endpoint:
```
class Spamnumber < LHS::Record
  endpoint ':datastore/v2/spamnumbers'
end
```
Console output when searching for a specific instance:
```
> Spamnumber.first._raw
=> {:number=>"0000000000", :formatted_number=>"000 000 00 00", :identity=>"Call Center", :source=>"local.ch", :frequency=>244, :user_frequency=>164, :report_frequency=>0, :stats_days=>90, :last_rank=>0, :diff_rank=>0, :description=>"Detected by local.ch", :last_updated=>"2015-10-23T07:20:11.956+01:00", :last_lookup=>"2015-10-20T16:40:51.000+02:00", :certainty=>90, :type=>"Unverified", :entry_id=>"nvPCqiT42X57Cc737-JJJg"}
> Spamnumber.find_by_formatted_number('031 508 75 77')
=> NoMethodError: undefined method `find_by_formatted_number' for Spamnumber:Class
	from (irb):4
	from /Users/francarast/.rvm/gems/ruby-2.1.7@location-app/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/francarast/.rvm/gems/ruby-2.1.7@location-app/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/francarast/.rvm/gems/ruby-2.1.7@location-app/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/francarast/.rvm/gems/ruby-2.1.7@location-app/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/francarast/.rvm/gems/ruby-2.1.7@location-app/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

_Expected_
Spamnumber.find_by_formatted_number('031 508 75 77') returns LHS::Record of Spamnumber with '031 508 75 77' as formatted_number

_Observed_
Undefined Method Error

**Comment by pape-io** [comment]
`find_by_*` was never implemented, which has multiple reasons.

`find_by(args)` is implemented, which is the `sane` way of using `find_by` anyway.

**Comment by pape-io** [comment]
In your case you would need to use:
```
find_by(formatted_number: '031 508 75 77')
```

**Comment by ryabrody** [comment]
I am a bit confused. Why does `find_by_email` work then as described in the README?
https://github.com/local-ch/lhs#very-short-introduction

**Comment by pape-io** [comment]
Oups, that documentation is outdated. I will remove it now. Will explain you why it's not so easy to implement `find_by_*` and we will see if we will (re)-implement sooner or later.

**Comment by ryabrody** [comment]
👍 okdoki

**Comment by ryabrody** [comment]
@pape-io 
That works:
```
irb(main):005:0> Spamnumber.find_by(formatted_number: '071 313 08 60')
=> <Spamnumber{:number=>"0000000000", :formatted_number=>"000 000 00 00", :identity=>"Call Center", :source=>"local.ch", :frequency=>244, :user_frequency=>164, :report_frequency=>0, :stats_days=>90, :last_rank=>0, :diff_rank=>0, :description=>"Detected by local.ch", :last_updated=>"2015-10-23T07:20:11.956+01:00", :last_lookup=>"2015-10-20T16:40:51.000+02:00", :certainty=>90, :type=>"Unverified", :entry_id=>"nvPCqiT42X57Cc737-JJJg"}>
```
